apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: transcendence
type: Opaque
stringData:
  DATABASE_URL: "postgres://transcendence:change-me@db:5432/transcendence"
  TB_CLUSTER_ID: "0"
  TB_IP_ADRESSES: "tigerbeetle:3000"
