sonar.projectKey=for-legal-reasons-this-is-game_For-legal-reasons-this-is-game
sonar.organization=for-legal-reasons-this-is-game

sonar.sources=backend,tradingengine
sonar.exclusions=**/target/**

sonar.rust.cargo.manifestPaths=backend/Cargo.toml,tradingengine/Cargo.toml
