// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountCodeType } from "./AccountCodeType";

export type AccountPayload = { name: string, ledger_symbol: string, code_type: AccountCodeType, };
