// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Ledger = { ledger_id: number, symbol: string, name: string, decimals: number, enabled: boolean, };
