// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountStatus } from "./AccountStatus";

export type Position = {
    account_id: string;
    account_status: AccountStatus;
    symbol: string;
    decimals: number;
    debits_posted: string;
    credits_posted: string;
    debits_pending: string;
    credits_pending: string;
    net_posted: string;
};
