CREATE TYPE order_submission AS ENUM ('reserving', 'sent', 'accepted', 'rejected');
CREATE TABLE IF NOT EXISTS orders (
  order_id UUID PRIMARY KEY,
  idempotency_key UUID NOT NULL UNIQUE, -- this key should be generated by the frontend so retries dont lead to duplicates
  command_id UUID NOT NULL UNIQUE,
  user_id UUID REFERENCES users(user_id) NOT NULL,
  market_id INTEGER REFERENCES markets(market_id) NOT NULL,
  base_account_id UUID REFERENCES accounts(account_id) NOT NULL,
  quote_account_id UUID REFERENCES accounts(account_id) NOT NULL,
  side SMALLINT NOT NULL CHECK (side IN (1, 2)),
  order_type SMALLINT NOT NULL CHECK (order_type BETWEEN 1 AND 4),
  time_in_force SMALLINT NOT NULL CHECK (time_in_force BETWEEN 1 AND 4),
  -- these are u128, 39,0 means 39 digits, 0 decimals
  base_quantity NUMERIC(39, 0),
  quote_quantity NUMERIC(39, 0),
  CONSTRAINT orders_one_quantity CHECK ((base_quantity IS NULL) <> (quote_quantity IS NULL)),
  limit_price NUMERIC(39, 0),
  trigger_price NUMERIC(39, 0),
  trigger_direction SMALLINT CHECK (trigger_direction IN (1, 2)),
  protection_price NUMERIC(39, 0),
  expire_time TIMESTAMPTZ,
  maker_fee_bps INTEGER NOT NULL,
  taker_fee_bps INTEGER NOT NULL,
  reserved_amount NUMERIC(39, 0) NOT NULL,
  -- the backend report
  submission order_submission NOT NULL DEFAULT 'reserving',
  reject_reason SMALLINT,
  reject_detail TEXT,
  -- the engine's report
  status SMALLINT CHECK (status BETWEEN 1 and 6),
  cancel_reason SMALLINT,
  filled_base_quantity NUMERIC(39, 0) NOT NULL DEFAULT 0,
  filled_quote_quantity NUMERIC(39, 0) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- index for orders to be filtered by user +  newest first, its just optimizing lookups
CREATE INDEX IF NOT EXISTS orders_user_created ON orders(user_id, created_at DESC);
-- index for open orders in a specifc market
CREATE INDEX IF NOT EXISTS orders_market_open ON orders(market_id)
WHERE submission <> 'rejected' AND (status IS NULL OR status IN (1, 2, 6));

CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER orders_set_updated_at
BEFORE UPDATE ON orders
FOR EACH ROW
WHEN (OLD.* IS DISTINCT FROM NEW.*)
EXECUTE FUNCTION set_updated_at();
